kind: Pod
apiVersion: v1
metadata:
  name: first-pod
  labels:
    app: http-echo
spec:
  containers:
  - name: foo-app
    image: dodexq/kuber_loadbalancing:v1
---
kind: Pod
apiVersion: v1
metadata:
  name: second-pod
  labels:
    app: http-echo
spec:
  containers:
  - name: bar-app
    image: dodexq/kuber_loadbalancing:v1
---
kind: Service
apiVersion: v1
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: http-echo
  ports:
  # Default port used by the image
  - port: 80
    targetPort: 4545
  type: LoadBalancer


